import React from 'react'
import Link from 'next/link'
import Head from 'next/head'
import  Image  from 'next/image'
import { useSession } from 'next-auth/react'
function page() {
  const {data: session} = useSession()
  
  
  return (
    <div className="h-full flex items-center justify-center">
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
      <div className="w-1/2 h-1/2 flex flex-col gap-10">

        {session ?
        <div className="bg-white p-10 items-center rounded-xl shadow-lg flex flex-col gap-6">
          <h2 className="text-4xl text-start w-full font-bold">Hello {session?.user?.firstname}</h2>
          <Link href="/create" className=" py-4 px-6 font-bold text-white text-xl w-full text-center rounded-full bg-secondary hover:scale-105 hover:shadow-lg transition-all active:scale-100">New invoice</Link>
        </div>
        :
        <Link href="/auth/signin" className="bg-secondary py-4 px-10  text-white font-bold rounded-full text-2xl hover:scale-105">Log in</Link>
        }
      </div>
    </div>
  )
}
export default page